### ISSUE TITLE
Precompiled testing_receiver_rgb.hex bricks Yj-14015?

### ISSUE THREAD

**Issue by TuTanK5** [joric/mitosis#1]
I have Yj-14015 soldered on the receiver board (only the Yj-14015, nothing else). After flashing testing_receiver_rgb.hex (flash successful - using openocd + stlink v2), Yj-14015 now seems bricked and cannot be reflashed. After checking with multi-meter, I find out that VCC and GND are shorted. 

I was dumb enough to do this twice, checking with the multimeter before flashing the second time, so I'm pretty sure it's not because of the soldering. 

How can I reflash it? Or my 2  Yj-14015s are done for?

**Comment by joric** [comment]
Never ever bricked anything. VCC and GND can't be normally shorted, check soldering.
